# Generated by Django 5.1.4 on 2026-05-15 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0010_alter_categorysection_kind'),
        ('stories', '0008_story_article_image_trendingtopic_comment_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('search', 'Search'), ('bookmark', 'Bookmark'), ('unbookmark', 'Unbookmark'), ('share', 'Share'), ('like', 'Like'), ('unlike', 'Unlike'), ('comment', 'Comment'), ('reaction', 'Reaction'), ('video_play', 'Video play'), ('transfer_open', 'Transfer card open'), ('session_start', 'Session start'), ('page_leave', 'Page leave')], db_index=True, max_length=24)),
                ('target_type', models.CharField(blank=True, db_index=True, default='', help_text="Soft reference — 'story', 'video', 'transfer', 'tag', 'category', etc.", max_length=32)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_label', models.CharField(blank=True, default='', help_text="Human-readable label captured at event time so dashboards don't need extra lookups.", max_length=240)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('device_type', models.CharField(blank=True, default='unknown', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form extra data — search query, share platform, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_643c3b_idx'), models.Index(fields=['target_type', 'target_id'], name='analytics_e_target__54d13e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=240)),
                ('kind', models.CharField(choices=[('home', 'Home'), ('story', 'Story'), ('category', 'Category'), ('section', 'Section'), ('tag', 'Tag'), ('transfers', 'Transfers'), ('gossip', 'Gossip'), ('opinion', 'Opinion'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('referrer', models.CharField(blank=True, default='', max_length=400)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=320)),
                ('device_type', models.CharField(blank=True, db_index=True, default='unknown', max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text="Time the visitor spent on this page before navigating away. Updated by a 'page_leave' event.")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='categories.category')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='stories.story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at', 'kind'], name='analytics_p_created_334fc1_idx'), models.Index(fields=['session_key', 'created_at'], name='analytics_p_session_9ecc08_idx')],
            },
        ),
    ]
