# Generated by Django 5.1.4 on 2026-04-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.CharField(default='⚽', help_text='Emoji icon', max_length=8)),
                ('color', models.CharField(default='#00A86B', help_text='Hex color e.g. #00A86B', max_length=9)),
                ('description', models.TextField(blank=True)),
                ('is_nav', models.BooleanField(default=False, help_text='Show in top navigation bar')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('order', 'name'),
            },
        ),
    ]
