# Generated by Django 5.1.4 on 2026-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Header hero image for the category page', null=True, upload_to='category_covers/'),
        ),
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Short tagline shown under the category name, e.g. 'EAPL to AFCON'", max_length=140),
        ),
    ]
