# Generated by Django 5.1.4 on 2026-05-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_categorysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysection',
            name='scope',
            field=models.CharField(choices=[('local', 'Local / East Africa'), ('international', 'International'), ('general', 'General')], default='general', help_text='Where this section sits in the Sports mega-menu: Local (EA leagues), International (global), or General (cross-cutting).', max_length=16),
        ),
        migrations.AlterField(
            model_name='categorysection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
