# Generated by Django 5.1.4 on 2026-05-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_remove_default_seeded_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysection',
            name='kind',
            field=models.CharField(choices=[('news', 'News'), ('scores', 'Scores'), ('results', 'Results'), ('transfers', 'Transfers'), ('fixtures', 'Fixtures'), ('standings', 'Standings'), ('teams', 'Teams'), ('players', 'Players'), ('videos', 'Videos'), ('custom', 'Custom page')], default='news', max_length=16),
        ),
    ]
