# Generated by Django 5.1.4 on 2026-04-21 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(default='Friendly', max_length=120)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('HT', 'Half Time'), ('FT', 'Full Time'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=16)),
                ('minute', models.CharField(blank=True, default='', max_length=8)),
                ('kickoff', models.DateTimeField(blank=True, null=True)),
                ('kickoff_display', models.CharField(blank=True, help_text="Optional overridden display, e.g. '15:00 EAT'", max_length=32)),
                ('venue', models.CharField(blank=True, max_length=160)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ('order', 'kickoff'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('flag', models.CharField(default='🏳', help_text='Emoji flag or short badge string', max_length=8)),
                ('short_name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GOAL', 'Goal'), ('YELLOW', 'Yellow Card'), ('RED', 'Red Card'), ('SUB', 'Substitution'), ('PEN', 'Penalty'), ('OG', 'Own Goal'), ('INFO', 'Info')], default='GOAL', max_length=8)),
                ('minute', models.PositiveIntegerField(default=0)),
                ('player', models.CharField(max_length=80)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scores.match')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.team')),
            ],
            options={
                'ordering': ('minute', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='scores.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='scores.team'),
        ),
    ]
