# Generated by Django 5.1.4 on 2026-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, help_text='Crest / badge image. Overrides flag when present.', null=True, upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.CharField(blank=True, default='', help_text='Emoji flag or short text badge (optional if logo uploaded)', max_length=16),
        ),
    ]
