# Generated by Django 5.1.4 on 2026-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_team_logo_alter_team_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.CharField(blank=True, default='', help_text="Provider's match id — used to upsert on sync", max_length=64),
        ),
        migrations.AddField(
            model_name='match',
            name='external_source',
            field=models.CharField(blank=True, default='', help_text="e.g. 'livescore-api' when auto-synced", max_length=40),
        ),
        migrations.AddField(
            model_name='match',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
