# Generated by Django 5.1.4 on 2026-04-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_match_external_id_match_external_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_visible',
            field=models.BooleanField(default=True, help_text="Show on the public live-scores strip. Uncheck to hide auto-synced matches you don't want featured."),
        ),
    ]
