# Generated by Django 5.1.4 on 2026-05-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_categorysection_scope_alter_categorysection_id'),
        ('scores', '0005_match_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=24, unique=True)),
                ('name', models.CharField(help_text="Display name, e.g. '2024/25'", max_length=24)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Marks the season currently being played. Used as default when stat queries omit a season.')),
            ],
            options={
                'ordering': ('-start_date', '-name'),
            },
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Sport this team plays. Drives where the team shows up in the navbar Teams listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='categories.category'),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='external_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='team',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text="Hex color used for the team-page accent (e.g. '#EF0107' for Arsenal red).", max_length=9),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('scope', models.CharField(choices=[('local', 'Local (East Africa)'), ('international', 'International')], default='international', max_length=16)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='competition_logos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('external_source', models.CharField(blank=True, default='', max_length=40)),
                ('external_id', models.CharField(blank=True, default='', help_text='Provider league id (e.g. api-football). Used by stats sync jobs.', max_length=64)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='categories.category')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward'), ('COACH', 'Coach / Manager'), ('OTHER', 'Other')], default='OTHER', max_length=8)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=80)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('external_source', models.CharField(blank=True, default='', max_length=40)),
                ('external_id', models.CharField(blank=True, default='', max_length=64)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='scores.team')),
            ],
            options={
                'ordering': ('position', 'jersey_number', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearances', models.PositiveIntegerField(default=0)),
                ('starts', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('clean_sheets', models.PositiveIntegerField(default=0, help_text='Goalkeeper-only stat. Ignored for outfield players.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='scores.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='scores.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='scores.season')),
            ],
            options={
                'ordering': ('-goals', '-assists'),
            },
        ),
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('position', models.PositiveIntegerField(blank=True, help_text='Current league table position (1 = top).', null=True)),
                ('clean_sheets', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='scores.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='scores.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='scores.team')),
            ],
            options={
                'ordering': ('position', '-points'),
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'position'], name='scores_play_team_id_6304cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerseasonstats',
            unique_together={('player', 'season', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='teamseasonstats',
            unique_together={('team', 'season', 'competition')},
        ),
    ]
