# Generated by Django 5.1.4 on 2026-05-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_season_team_category_team_country_team_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='primary_competition',
            field=models.ForeignKey(blank=True, help_text='Current / main league this team plays in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_teams', to='scores.competition'),
        ),
    ]
