# Generated by Django 5.1.4 on 2026-04-21 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(default='0:00', help_text="e.g. '8:24'", max_length=16)),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbs/')),
                ('gradient', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(choices=[('Highlights', 'Highlights'), ('Documentary', 'Documentary'), ('Feature', 'Feature'), ('Interview', 'Interview'), ('Analysis', 'Analysis')], default='Highlights', max_length=40)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='categories.category')),
            ],
            options={
                'ordering': ('-is_featured', '-published_at'),
            },
        ),
    ]
