# Generated by Django 5.1.4 on 2026-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_tag_story_story_format_story_tags'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='stories.tag'),
        ),
    ]
