# Generated by Django 5.1.4 on 2026-04-21 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('link_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Breaking news items',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('headline', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='story_covers/')),
                ('gradient', models.CharField(blank=True, help_text="Tailwind gradient, e.g. 'from-amber-900/80 via-orange-900/60 to-navy'", max_length=160)),
                ('placement', models.CharField(choices=[('none', 'None'), ('hero', 'Hero'), ('featured', 'Featured'), ('top', 'Top Stories'), ('editors_pick', "Editor's Pick")], default='none', max_length=16)),
                ('placement_rank', models.PositiveIntegerField(default=0, help_text='Lower = higher on page. Used to order featured/top/ep stories.')),
                ('editors_pick_type', models.CharField(blank=True, choices=[('', '—'), ('longform', 'Longform'), ('analysis', 'Analysis'), ('opinion', 'Opinion')], default='', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=12)),
                ('is_live', models.BooleanField(default=False)),
                ('is_breaking', models.BooleanField(default=False)),
                ('read_minutes', models.PositiveIntegerField(default=3)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='TrendingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=48, unique=True)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order', '-post_count'),
            },
        ),
    ]
