# Generated by Django 5.1.4 on 2026-04-21 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='categories.category'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['placement', 'placement_rank'], name='stories_sto_placeme_fd69b6_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status', '-published_at'], name='stories_sto_status_386c74_idx'),
        ),
    ]
