# Generated by Django 5.1.4 on 2026-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='story',
            name='story_format',
            field=models.CharField(choices=[('news', 'News'), ('analysis', 'Analysis'), ('opinion', 'Opinion'), ('interview', 'Interview'), ('feature', 'Feature'), ('match_preview', 'Match Preview'), ('match_report', 'Match Report'), ('live_blog', 'Live Blog'), ('quick_hit', 'Quick Hit')], default='news', help_text='Editorial format/genre — drives the badge style on cards', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='stories', to='stories.tag'),
        ),
    ]
