# Generated by Django 5.1.4 on 2026-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_tag_story_story_format_story_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_format',
            field=models.CharField(choices=[('news', 'News'), ('analysis', 'Analysis'), ('opinion', 'Opinion'), ('interview', 'Interview'), ('feature', 'Feature'), ('match_preview', 'Match Preview'), ('match_report', 'Match Report'), ('live_blog', 'Live Blog'), ('quick_hit', 'Quick Hit'), ('gossip', 'Gossip')], default='news', help_text='Editorial format/genre — drives the badge style on cards', max_length=20),
        ),
    ]
