# Generated by Django 5.1.4 on 2026-05-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_story_story_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakingnews',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this alert auto-disappears from the ticker. Leave blank to never expire. Defaults to 60 minutes after creation.', null=True),
        ),
    ]
