# Generated by Django 5.1.4 on 2026-05-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_categorysection_scope_alter_categorysection_id'),
        ('stories', '0005_breakingnews_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakingnews',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Sport this alert belongs to. Leave blank for cross-sport alerts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breaking_items', to='categories.category'),
        ),
        migrations.AddField(
            model_name='trendingtopic',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Sport this trend belongs to. Leave blank for cross-sport trends.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trending_topics', to='categories.category'),
        ),
    ]
