# Generated by Django 5.1.4 on 2026-05-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_breakingnews_category_trendingtopic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtopic',
            name='body',
            field=models.TextField(blank=True, help_text="Markdown intro shown above the story list on the trending tag's page."),
        ),
    ]
