# Generated by Django 5.1.4 on 2026-04-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('breaking', 'Breaking only')], default='daily', max_length=16)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('confirm_token', models.CharField(blank=True, max_length=48, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='site', max_length=60)),
            ],
            options={
                'ordering': ('-subscribed_at',),
            },
        ),
    ]
