# Generated by Django 5.1.4 on 2026-05-15 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0010_alter_categorysection_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('player_name', models.CharField(max_length=160)),
                ('player_photo', models.ImageField(blank=True, null=True, upload_to='transfer_player_photos/')),
                ('from_club', models.CharField(blank=True, default='', help_text='Selling / parent club. Leave blank for free agents.', max_length=160)),
                ('from_club_logo', models.ImageField(blank=True, null=True, upload_to='transfer_club_logos/')),
                ('to_club', models.CharField(blank=True, default='', help_text='Destination club. Leave blank if not yet known (e.g. rumour stage).', max_length=160)),
                ('to_club_logo', models.ImageField(blank=True, null=True, upload_to='transfer_club_logos/')),
                ('transfer_status', models.CharField(choices=[('rumor', 'Rumour'), ('talks', 'In talks'), ('agreed', 'Agreement reached'), ('medical', 'Medical scheduled'), ('here_we_go', 'Here we go'), ('completed', 'Completed'), ('loan', 'Loan move'), ('rejected', 'Rejected / failed')], default='rumor', max_length=16)),
                ('fee', models.CharField(blank=True, default='', help_text="Display string — e.g. '€85M', 'Free transfer', 'Undisclosed'.", max_length=64)),
                ('contract_length', models.CharField(blank=True, default='', help_text="e.g. '5 years', 'Until 2028'.", max_length=64)),
                ('reliability', models.PositiveSmallIntegerField(choices=[(1, '1 / 5'), (2, '2 / 5'), (3, '3 / 5'), (4, '4 / 5'), (5, '5 / 5')], default=3, help_text='How solid is this report? 1 = speculation, 5 = officially confirmed.')),
                ('summary', models.CharField(blank=True, default='', help_text='One-sentence blurb shown on cards.', max_length=400)),
                ('body', models.TextField(blank=True, default='', help_text='Full write-up (markdown / plain text).')),
                ('source', models.CharField(blank=True, default='', help_text="Original reporter / outlet — e.g. 'Fabrizio Romano', 'BBC Sport'.", max_length=120)),
                ('source_url', models.URLField(blank=True, default='')),
                ('is_featured', models.BooleanField(default=False, help_text='Pin to the top of the transfer-news strip.')),
                ('is_breaking', models.BooleanField(default=False, help_text="Glow + animated 'BREAKING' chip on the card. Reserve for the big moments.")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=12)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_news', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Sport this transfer belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_news', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Transfer news',
                'ordering': ('-is_featured', '-published_at'),
                'indexes': [models.Index(fields=['status', '-published_at'], name='transfers_t_status_ac10d2_idx'), models.Index(fields=['category', '-published_at'], name='transfers_t_categor_da3a62_idx')],
            },
        ),
    ]
